---
title: "wbh_heatmaps"
author: "Tyler Akonom"
date: "1/8/2025"
output: html_document
---

```{r setup, include=FALSE}
require("knitr")
knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir = "C:\\GitHub\\Lowry-WBH\\deseq_out\\")
outdir <- "C:\\GitHub\\Lowry-WBH\\deseq_out\\"
library(dplyr)
library(DESeq2)
library(knitr)
library(ggplot2)
library(magrittr)
library(tidyr)
library(tibble)
library(ComplexHeatmap)
#library(DEGreport)
library(vsn)
library(rrcov)
library(sva)
library(circlize)
library(EnhancedVolcano)
```



# --------- Generating heatmaps of significant GSEA results --------

```{r}
setwd("C:\\GitHub\\Lowry-WBH\\deseq_out\\")

pos <- read.csv("gsea_pos.csv", header = TRUE)
neg <- read.csv("gsea_neg.csv", header = TRUE)
norm <- read.csv("C:\\GitHub\\Lowry-WBH\\deseq_out\\norm_counts.csv", row.names = 1)

# Selecting each variable in sample ids. M (male), F (female), S (sham), T (treatment)
norm_m <- select(norm, contains("M"))
norm_f <- select(norm, contains("F"))
norm_s <- select(norm, contains("S"))
norm_t <- select(norm, contains("T"))

# Generated in "wbh_deseq2.rmd"
zscore <- read.csv("C:\\GitHub\\Lowry-WBH\\deseq_out\\zscore.csv", row.names = 1)

posfwer <- filter(pos, FWER.p.val < 0.05)
posbps <- paste(posfwer$NAME)
postsv <- paste0(posbps, ".tsv")

negfwer <- filter(neg, FWER.p.val < 0.05)
negbps <- paste(negfwer$NAME)
negtsv <- paste0(negbps, ".tsv")

bps <- c(posbps, negbps)
tsv <- c(postsv, negtsv)

for(i in c(1:length(bps))){
     name <- bps[[i]]    
     assign (name, read.csv(paste0("C:\\GitHub\\Lowry-WBH\\gsea\\C5_GOBP\\treatment_wbh.GseaPreranked.1680722207986\\", bps[i], ".tsv"), sep = "\t",
                            colClasses = c('character','character', 'numeric', 'numeric', 'numeric', 'factor', 'factor')
                            ))}

list <- mget(bps)
flist <- lapply(list, function(df){
  df <- df %>% select(SYMBOL, CORE.ENRICHMENT)
  df$CORE.ENRICHMENT <- factor(df$CORE.ENRICHMENT)
  df <- df %>% filter(CORE.ENRICHMENT == "Yes")
  df <- as.data.frame(zscore) %>% filter(rownames(zscore) %in% df$SYMBOL)
  df
})
```



```{r}
data_list <- flist
col_fun = circlize::colorRamp2(c(-2, 0, 2), c("blue", "white", "red"))

# Function to generate heatmap for each data frame in the list

generate_heatmaps <- function(data_list) {
  for (name in names(data_list)) {
    # Create Heatmap object
    heatmap_object <- Heatmap(as.matrix(data_list[[name]]),
                              name = "zscore",
                              cluster_columns = FALSE,
                              col = col_fun,
                              row_names_gp = gpar(fontsize = 14),
                              row_title_rot = 90,
                              row_title_side = "left",
                              row_names_side = "left",
                              column_title_side = "top",
                              column_names_rot = 90,
                              show_column_names = TRUE,
                              show_row_dend = FALSE,
                              show_column_dend = FALSE,
                              # column_split = c("1-SS", "1-SS", "1-SS", "1-SS", "1-SS", "2-OS", "2-OS", "2-OS", "2-OS"),
                              heatmap_width = unit(4, "npc"),
                              heatmap_height = unit(8, "npc"),
                              heatmap_legend_param = list(legend_height = unit(.5, "npc"), legend_width = unit(.2, "npc"), title_position = "topcenter")                             
                              )
    
    # Plot Heatmap
    draw(heatmap_object, heatmap_legend_side = "left")
    
    # Export as PNG
    filename <- paste(name, ".png", sep = "")
    dev.copy(png, filename, width = 300, height = 800, units = "px")
    dev.off()
    cat(name, "exported as", filename, "\n")
  }
}

# Call the function to generate heatmaps for each data frame
setwd("C:\\GitHub\\Lowry-WBH\\gsea\\heatmaps\\")
generate_heatmaps(data_list)
```